server:
  port: 8762


spring:
  zipkin:
    base-url: http://localhost:9411

#  rabbitmq:
#    host: localhost
#    port: 5672
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.128:3306/sys-user?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: 192.168.2.128
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true
    virtual-host: /

foo: foo version 1