server:
  port: 9998

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registryFetchIntervalSeconds: 5
  instance:
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream #,activiti
#      turbine:
#        clusters: default
#        location: monitor-service
  security:
    user:
      name: 'admin'
      password: '123456'

logging:
  file: "logs/admin-service-pro.log"