server:
  port: 9998

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#    registryFetchIntervalSeconds: 5
#  instance:
#    metadata-map:
#      user.name: admin
#      user.password: 123456
#    leaseRenewalIntervalInSeconds: 10
#    health-check-url-path: /actuator/health #2.0后actuator的地址发生了变化

management:
  security:
    enabled: false

#security:
#  user:
#    name: admin
#    password: 123456

spring:
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream #,activiti
#      turbine:
#        clusters: default
#        location: monitor-service

logging:
  file: "logs/admin-service-pro.log"