server:
  port: 9998
#security:
#  user:
#    name: admin
#    password: admin
management:
  security:
    enabled: false

#spring:
#  boot:
#    admin:
#      routes:
#        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,activiti
#      turbine:
#        clusters: default
#        location: monitor-service
#
eureka:
  instance:
    metadata-map:
      user.name: admin
      user.password: admin
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health #2.0后actuator的地址发生了变化
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#    registryFetchIntervalSeconds: 5
#
#logging:
#  file: "logs/admin-service-pro.log"ac