server:
  port: 8763

eureka:
  client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

management:
  security:
    enabled: true
    user:
      name: "admin"
      password: "123456"
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  hystrix:
    enabled: true

spring:
  zipkin:
    base-url: http://localhost:9411

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys-blog?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 1234

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true
    virtual-host: /

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl