server:
  port: 8766

eureka:
  client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

management:
  security:
    enabled: false

security:
  basic:
    enabled: false

turbine:
  aggregator:
    clusterConfig: default
  appConfig: user-service , blog-service
  clusterNameExpression: new String("default")
#security:
#  user:
#    name: admin
#    password: admin

