server:
  port: 8766
security.basic.enabled: false
turbine:
  aggregator:
    clusterConfig: default
  appConfig: user-service , blog-service , test , test2
  clusterNameExpression: new String("default")
#security:
#  user:
#    name: admin
#    password: admin
management:
  security:
    enabled: false

eureka:
  client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/