server:
  port: 8762

eureka:
  client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

spring:
  zipkin:
    base-url: http://localhost:9411
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.128:3306/sys-user?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 1234
  rabbitmq:
    host: 192.168.2.128
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true
    virtual-host: /

feign:
  hystrix:
    enabled: true
#security:
#  user:
#    name: admin
#    password: admin
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: *
#mybatis-plus:
#  mapper-locations: classpath*:com/example/userservice/mapper/**/*Mapper.xml
#  type-aliases-package: com.example.userservice.entity
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl