spring:
  rabbitmq:
    host: 192.168.2.128
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true
    virtual-host: /
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.128:3306/springcloud?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
      name: log-service
