server:
  port: 8769

spring:
  application:
    name: config-server

  profiles:
    active: native
  cloud:
    config:
      server:
#        native: #本地配置
#          search-locations: classpath:/shared
        git:
          uri: https://github.com/hyosunghan/springcloud
          search-paths: config
      label: master