server:
  port: 8769

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hyosunghan/demo_springcloud
          search-paths: config
          username:
          password:
#        native:
#          search-locations: classpath:/shared
      label: master