server:
  port: 8769

spring:
  application:
    name: config-server

  profiles:
    active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: classpath:/shared
        git:
          uri: https://github.com/hyosunghan/springcloud
          search-paths: shared